spring:
  application:
    name: study-project

  data:
    mongodb:
      uri: ${DB_URI}

server:
  port: 8080

api:
  key: ${API_KEY}

tweet-import:
  file-paths: classpath:data/realDonaldTrump_in_office.csv,classpath:data/realDonaldTrump_bf_office.csv
  batch-size: 1000
  remove-hashtag: true
  remove-mention: true
  remove-emoji: true